# Простой скрипт для создания релиза
Write-Host "=========================================="
Write-Host "Создание релиза CloakVPN v1.0.0"
Write-Host "=========================================="
Write-Host ""
Write-Host "Тег v1.0.0 пересоздан и готов к использованию!"
Write-Host ""
Write-Host "Для создания релиза:"
Write-Host ""
Write-Host "1. Откройте: https://github.com/Rew1x3/CloakVPN_Programm/releases/new"
Write-Host ""
Write-Host "2. В поле 'Choose a tag' выберите 'v1.0.0' из выпадающего списка"
Write-Host "   (НЕ вводите вручную - выберите из списка существующих тегов!)"
Write-Host ""
Write-Host "3. Если тега нет в списке, нажмите 'Create new tag: v1.0.0'"
Write-Host "   и выберите последний коммит из ветки main"
Write-Host ""
Write-Host "4. Название релиза: CloakVPN v1.0.0 - Initial Release"
Write-Host ""
Write-Host "5. Скопируйте содержимое из файла release_notes.md в описание"
Write-Host ""
Write-Host "6. Нажмите 'Publish release'"
Write-Host ""
Write-Host "=========================================="
Write-Host ""
Write-Host "Проверка тега на GitHub..."
git ls-remote --tags origin | Select-String "v1.0.0"
Write-Host ""
Write-Host "Тег должен быть виден выше. Если нет - подождите несколько секунд."


